config/routes.rb
Rails1::Application.routes.draw do
  root :to => "articles#index"
  resources :articles
  

end

app/models/article.rb
class Article < ActiveRecord::Base
	validates :title, presence: true,

    	length: { minimum: 5 }

    validates :content, presence: true,

        length: { minimum: 10 }

    validates :status, presence: true

    scope :status_active, -> {where(status: 'active')}

    default_scope {where(status: 'active')}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
     @articles = Article.all
  end

  def new
  	@article = Article.new
  end

  def edit
        @article = Article.find_by_id(params[:id])
  end

  def create
    @article = Article.new(params_article)

    if @article.save

        flash[:notice] = "Success Add Records"

        redirect_to action: 'index'

    else

        flash[:error] = "data not valid"

        render 'new'
  end

  #def index
  # @articles = Article.all
  #end

  def show

        @article = Article.find_by_id(params[:id])

  end

  def update

 @article = Article.find_by_id(params[:id])

 if @article.update(params_article)

    flash[:notice] = "Success Update Records"

    redirect_to action: 'index'

 else

    flash[:error] = "data not valid"

    render 'edit'

 end
  def destroy

    @article = Article.find_by_id(params[:id])

    if @article.destroy

        flash[:notice] = "Success Delete a Records"

        redirect_to action: 'index'

    else

        flash[:error] = "fails delete a records"

        redirect_to action: 'index'

    end

end
end
  private

    def params_article

        params.require(:article).permit(:title, :content, :status)

    end

  end
end

   

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/edit.html.erb
<h1>Articles#edit</h1>
<p>Find me in app/views/articles/edit.html.erb</p>
 <%= form_for @article do |f| %>

<%= f.label :title %>

<%= f.text_field :title %>

<br/>

<%= f.label :content %>

<%= f.text_area :content, cols: 20, rows: 10 %>

<br/>

<%= f.label :status %>

<%= f.radio_button :status, "active" %>

<%= label :article_status, 'active' %>

<%= f.radio_button :status, "off" %>

<%= label :article_status, 'off' %>

<br/>

<%= f.submit :submit %>

<% end %>


<div>

<%= link_to "back to index", articles_path %>

</div>

app/views/articles/index.html.erb
<h1>Articles#index</h1>
<p>Find me in app/views/articles/index.html.erb</p>
 

 <% @articles.each do |article| %>

<h3><%= article.title %></h3>

<p><%= article.content %></p>

<h4>status : <%= article.status %></h4>

<p>

<span><%= link_to 'edit', edit_article_path(article.id) %><span>

</p>

<hr/> 
% @articles.each do |article| %>

<h3><%= article.title %></h3>

<p><%= article.content %></p>

<h4>status : <%= article.status %></h4>

<p>

<span><%= link_to 'edit', edit_article_path(article.id) %><span>

<span> | </span>

<span><%= link_to 'delete', article_path(article.id), method: "DELETE", data: {confirm: 'Delete this data ? '} %><span>

</p>

<hr/>

<% end %>

app/views/articles/new.html.erb
<h1>Articles#new</h1>
<p>Find me in app/views/articles/new.html.erb</p>

 <%= form_for @article do |f| %>

<%= f.label :title %>

<%= f.text_field :title %>
<%= @article.errors[:title].first unless @article.errors[:title].blank? %>

<br/>

<%= f.label :content %>

<%= f.text_area :content, cols: 20, rows: 10 %>
<%= @article.errors[:content].first unless @article.errors[:content].blank? %>

<br/>

<%= f.label :status %>

<%= f.radio_button :status, "active" %>

<%= label :article_status, 'active' %>

<%= f.radio_button :status, "off", :checked => true %>

<%= label :article_status, 'off' %>

<br/>

<%= f.submit :submit %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails1</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>